version: '3'
services:
  app:
    image: kimbumsoo99/cicd:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: ssafytest
    ports:
      - "3306:3306"
